apiVersion: v1
kind: Service
metadata:
  name: news-classifier-service
  labels:
    app: news-classifier
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: news-classifier
